openapi: 3.0.3
info:
  title: El Greco Webapp API
  version: 0.1.0
servers:
  - url: https://YOUR-RENDER-DOMAIN
paths:
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
                password: { type: string }
      responses:
        '200': { description: OK }
        '429': { description: Too many attempts }
  /api/paintings:
    get:
      summary: List paintings (optional pagination via page/limit)
      parameters:
        - in: query
          name: page
          schema: { type: integer, minimum: 0 }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100 }
      responses:
        '200': { description: OK }
    post:
      summary: Create painting
      responses:
        '201': { description: Created }


# x-smart-pagination: Αν δεν δοθούν page/limit, ο server εφαρμόζει paginate μόνο όταν total>12, αλλιώς επιστρέφει όλα.
