name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run backend checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint -- --max-warnings=0

      - name: Run tests
        run: npm test

      - name: Upload test coverage
        if: success() && hashFiles('backend/coverage/lcov.info') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: backend/coverage/
